language: php

sudo: false

addons:
  apt:
    packages:
      - tidy

before_install:
  - pip install --user codecov

env:
  global:
    - DB=MYSQL CORE_RELEASE=3.1

    # Turn coverage off by default, as it's expensive time wise
    - COVERAGE=0

matrix:
  allow_failures:
    - php: hhvm-nightly
  include:
    - php: 5.6
      env: DB=MYSQL CORE_RELEASE=3.5.1


before_script:
  - phpenv rehash
  - composer self-update || true
  - git clone git://github.com/silverstripe-labs/silverstripe-travis-support.git ~/travis-support
  - php ~/travis-support/travis_setup.php --source `pwd` --target ~/builds/ss --require "silverstripe/comments" --require "silverstripe/widgets"
  - cd ~/builds/ss
